### PR TITLE
Strip trailing slashes from image src. This fixes images not getting res...

### PR DESCRIPTION
**Pull request by enfold-josh**
...olved when inserted as original size by plone.app.widgets tinymce.

### CODE REVIEW

**Comment by jensens** [comment]
- no contributor agreement signed - see https://plone.org/foundation/contributors-agreement
- needs quick review by someone familar with outputfilters

**Comment by thet** [comment]
Wow, that's a commit from 2014! It definetly solves a problem which occurred on a site with plone.app.wigets and newest mockup code on inserting some images with tinyMCE.

here ist the jenkins job: http://jenkins.plone.org/job/pull-request-5.0/382/

**Comment by thet** [comment]
- There is no test for this, but might not be needed either.
Looks good for me. Let's see the test result.

@enfold-josh did you sign and send the contributor agreement https://plone.org/foundation/contributors-agreement ?

**Comment by jensens** [comment]
since this is a one liner our release manager would be allowed to merge this anyway.
cc @esteele

**Comment by thet** [comment]
I think this should go in the next Plone 5.0 release. It fixes an annoying bug in tinyMCE. cc @esteele

**Comment by thet** [comment]
Another try: http://jenkins.plone.org/job/pull-request-5.0/395/

**Comment by jensens** [comment]
is there a matching bug in Products.CMFPlone issue tracker? Otherwise I propose to create it (looking :point_right: @thet). :smile:

**Comment by thet** [comment]
I just recognized, that one problem with resolving image urls had a completly different cause. I also tried to reproduce the problem with inserting a original-size image with tinyMCE, which works just fine.
Maybe this pull-request is obsolete. Furthermore we have failing jenkins tests (see links above). But I think they should not have much to do with this change.
However, I'm closing this pull request unmerged.

**Pull request closed without merging**
